name: CD

on:
  push:
    tags:
      - 'v*'
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --console=plain
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.VERSION }}"
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ### Installation

            #### Maven

            ```
            <dependency>
              <groupId>me.paulschwarz</groupId>
              <artifactId>spring-dotenv</artifactId>
              <version>${{ steps.get_version.outputs.VERSION }}</version>
            </dependency>
            ```

            #### Gradle

            ```
            implementation 'me.paulschwarz:spring-dotenv:${{ steps.get_version.outputs.VERSION }}'
            ```

            #### Ivy

            ```
            <dependency org='me.paulschwarz' name='spring-dotenv' rev='${{ steps.get_version.outputs.VERSION }}'>
              <artifact name='spring-dotenv' ext='pom' />
            </dependency>
            ```
      - name: Publish
        run: ./gradlew bintrayUpload --console=plain
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}   
          BINTRAY_GPGPASSPHRASE: ${{ secrets.BINTRAY_GPGPASSPHRASE }}
